

import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/heroScrollToTop";
import FloatingWhatsApp from "@/components/FloatingWhatsApp";
// import DarkLight from "@/components/DarkLight";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "اب بنے گا Digital پاکستان | Egrif",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (

    <html lang="en" className={poppins.className} suppressHydrationWarning 
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
        (function() {
          try {
            const theme = localStorage.getItem("theme");
            if (theme === "dark") {
              document.documentElement.classList.add("dark");
            }
          } catch (e) {}
        })();
      `,
          }}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className="transition-colors duration-500 ">

        <Header />
        {/* <DarkLight/> */}

        {children}
        <FloatingWhatsApp />
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
